spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raindream_database
    username: user
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

raindream:
  jwt:
    secret-key: hYW3L6I3gPpEUbtU+17FEHRYJuc8uLYHaLLsuzzyKn4=
  oss:
    endpoint: ${OSS_ENDPOINT:oss-cn-shanghai.aliyuncs.com}
    bucket: ${OSS_BUCKET:raindream}
    access-key-id: ${OSS_ACCESS_KEY_ID:}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
    expires-seconds: ${OSS_PRESIGN_EXPIRES_SECONDS:300}
    read-expires-seconds: ${OSS_PRESIGN_READ_EXPIRES_SECONDS:600}
    public-domain: ${OSS_PUBLIC_DOMAIN:}
